# SwiftLint Configuration for firstmenu
# https://github.com/realm/SwiftLint

# Disabled rules (firstmenu-specific choices)
disabled_rules:
  - trailing_whitespace
  - todo
  - large_tuple  # Domain models use tuples for data transfer

# Opt-in rules for stricter code quality
opt_in_rules:
  - explicit_init
  - first_where
  - fatal_error_message
  - force_unwrapping
  - implicitly_unwrapped_optional
  - closure_spacing
  - overridden_super_call
  - conditional_returns_on_newline
  - empty_count
  - empty_string
  - explicit_type_interface
  - fallthrough
  - file_name
  - function_default_parameter_at_end
  - multiline_parameters
  - operator_usage_whitespace
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Paths to include
included:
  - firstmenu

# Paths to exclude
excluded:
  - firstmenuTests
  - firstmenuUITests

# Configurable rules
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 600

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - db
    - url
    - URL
    - app

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2

# Custom rules for firstmenu architecture
custom_rules:
  domain_no_import:
    name: "Domain Should Not Import UI/Frameworks"
    regex: "import (SwiftUI|AppKit|UIKit)"
    match_kinds:
      - keyword
    message: "Domain layer should not import UI frameworks."
    excluded:
      - ".*UI.*"
      - ".*App.*"

  infrastructure_actor:
    name: "Infrastructure Should Use Actor"
    regex: "public (class|struct) (\\w+): (\\w+Providing)"
    match_kinds:
      - keyword
    message: "Infrastructure providers should be actors for thread safety."
    excluded:
      - ".*Tests.*"

# Reporter configuration
reporter: "xcode"
